CREATE TABLE IF NOT EXISTS visits (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 url TEXT NOT NULL,
 protocol TEXT NOT NULL,
 visited_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_visits_id ON visits(id DESC);

CREATE TABLE IF NOT EXISTS bookmarks (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 url TEXT UNIQUE NOT NULL,
 title TEXT NOT NULL,
 created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS servers (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 hostname TEXT NOT NULL UNIQUE,
 protocol TEXT NOT NULL,
 origin TEXT NOT NULL,
 created_at TEXT NOT NULL,
 updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_servers_protocol_hostname ON servers(protocol,hostname);
