name="fairwas"
compatibility_date="2026-10-08"
compatibility_flags=["nodejs_compat"]
pages_build_output_dir="./dist"

[[d1_databases]]
binding="pages"
database_name="workers-pages"
database_id="9826cce7-68c1-41f5-a5db-4e9db9caf992"
preview_database_id="pages"

[[d1_databases]]
binding="server"
database_name="server"
database_id="9bfa7efc-5ff4-4bf7-989c-171546b1c121"
preview_database_id="server"

[[d1_databases]]
binding="database"
database_name="database"
database_id="cdbf74ac-569d-4304-89bc-842384dee141"
preview_database_id="database"

[[d1_databases]]
binding="users"
database_name="users"
database_id="e13c0728-7e13-458f-a19b-fdf54ee78f02"
preview_database_id="users"
