const MAX_FILES=300;
const MAX_BYTES=15*1024*1024;
const TEXT=/^(text\/|application\/(?:json|javascript|xml|svg\+xml|manifest\+json))/i;
const STATIC_EXT=/\.(?:html?|css|js|mjs|json|svg|xml|txt|webmanifest|png|jpe?g|gif|webp|avif|ico|bmp|woff2?|ttf|otf|eot|mp3|wav|ogg|mp4|webm|wasm|map)$/i;
function cleanPath(path){let p=String(path||"/").split("?")[0].split("#")[0].replace(/\\/g,"/");if(!p.startsWith("/"))p="/"+p;p=p.replace(/\/+/g,"/");return p==="/"?"/index.html":p}
function sameOrigin(a,b){return a.protocol===b.protocol&&a.hostname===b.hostname&&a.port===b.port}
function unsafeHost(host){const h=String(host||"").toLowerCase();if(h==="localhost"||h.endsWith(".localhost")||h.endsWith(".local")||h.endsWith(".internal"))return true;const m=h.match(/^\d+\.\d+\.\d+\.\d+$/);if(!m)return false;const p=h.split(".").map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)}
function b64(bytes){let s="";for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
function isText(type,path){return TEXT.test(type)||/\.(?:html?|css|js|mjs|json|svg|xml|txt|webmanifest|map)$/i.test(path)}
function refs(source,base){
 const found=new Set(),text=String(source||"");
 const add=(raw)=>{const value=String(raw||"").trim().replace(/^["']|["']$/g,"");if(!value||value.startsWith("#")||/^(?:data:|javascript:|mailto:|tel:|blob:|https?:\/\/[^/]*$)/i.test(value))return;try{const u=new URL(value,base);if(/^https?:$/.test(u.protocol))found.add(u.href)}catch{}};
 const attrs=/(?:href|src|poster|data-src|action|xlink:href|srcset)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/gi;
 for(const m of text.matchAll(attrs)){const value=m[1]??m[2]??m[3]??"";if(/srcset/i.test(m[0].slice(0,m[0].indexOf("=")))){for(const candidate of value.split(","))add(candidate.trim().split(/\s+/)[0])}else add(value)}
 const css=/url\(\s*["']?([^"')]+)["']?\s*\)|@import\s+(?:url\()?\s*["']([^"')\s;]+)["']?/gi;
 for(const m of text.matchAll(css))add(m[1]||m[2]);
 const modules=/(?:\bimport\s*(?:[^'"]*?\sfrom\s*)?|\bexport\s+[^'"]*?\sfrom\s*|\bimport\s*\()\s*["']([^"']+)["']/g;
 for(const m of text.matchAll(modules))add(m[1]);
 return [...found];
}
function localize(source,base,map){
 const local=(raw)=>{try{const u=new URL(raw,base);if(!/^https?:$/.test(u.protocol)||u.hostname!==base.hostname||u.port!==base.port)return null;return map.get(cleanPath(u.pathname))||null}catch{return null}};
 let output=String(source||"");
 output=output.replace(/((?:href|src|poster|data-src|action|xlink:href)\s*=\s*["'])([^"']+)(["'])/gi,(all,prefix,raw,suffix)=>{const path=local(raw);if(!path)return all;try{const u=new URL(raw,base);return prefix+path+(u.search||"")+(u.hash||"")+suffix}catch{return all}});
 output=output.replace(/(srcset\s*=\s*["'])([^"']+)(["'])/gi,(all,prefix,value,suffix)=>{const rewritten=value.split(",").map(candidate=>{const parts=candidate.trim().split(/\s+/);const path=local(parts[0]);if(path){try{const u=new URL(parts[0],base);parts[0]=path+(u.search||"")+(u.hash||"")}catch{}}return parts.join(" ")}).join(", ");return prefix+rewritten+suffix});
 output=output.replace(/url\(\s*(["']?)([^"')]+)\1\s*\)/gi,(all,q,raw)=>{const path=local(raw.trim());if(!path)return all;try{const u=new URL(raw.trim(),base);return "url("+q+path+(u.search||"")+(u.hash||"")+q+")"}catch{return all}});
 output=output.replace(/(@import\s+(?:url\(\s*)?)(["'])([^"']+)\2(\s*\)?)/gi,(all,prefix,q,raw,suffix)=>{const path=local(raw);if(!path)return all;try{const u=new URL(raw,base);return prefix+q+path+(u.search||"")+(u.hash||"")+q+suffix}catch{return all}});
 output=output.replace(/((?:\bimport\s*(?:[^'"]*?\sfrom\s*)?|\bexport\s+[^'"]*?\sfrom\s*|\bimport\s*\()\s*)(["'])([^"']+)\2/g,(all,prefix,q,raw)=>{const path=local(raw);if(!path)return all;try{const u=new URL(raw,base);return prefix+q+path+(u.search||"")+(u.hash||"")+q}catch{return all}});
 return output;
}
export async function onRequestPost({request}){let body;try{body=await request.json()}catch{return Response.json({ok:false,error:"invalid_json"},{status:400})}let root;try{root=new URL(String(body.url||""))}catch{return Response.json({ok:false,error:"invalid_url"},{status:400})}if(!/^https?:$/.test(root.protocol))return Response.json({ok:false,error:"only_http_https_sources_allowed"},{status:400});if(unsafeHost(root.hostname))return Response.json({ok:false,error:"unsafe_source_host"},{status:400});root.hash="";root.search="";const queue=[root.href],seen=new Set(),files=[],total={bytes:0};while(queue.length&&files.length<MAX_FILES&&total.bytes<MAX_BYTES){const href=queue.shift();if(seen.has(href))continue;seen.add(href);let u;try{u=new URL(href)}catch{continue}if(!sameOrigin(u,root)||unsafeHost(u.hostname))continue;let response;try{response=await fetch(u.href,{redirect:"manual",headers:{"user-agent":"Fairwas-Static-Migrator/2.0"}})}catch{continue}if(response.status>=300&&response.status<400){const loc=response.headers.get("location");if(loc)try{const next=new URL(loc,u);if(sameOrigin(next,root))queue.push(next.href)}catch{}continue}if(!response.ok)continue;const finalUrl=new URL(response.url||u.href);if(!sameOrigin(finalUrl,root))continue;const type=(response.headers.get("content-type")||"application/octet-stream").split(";")[0].toLowerCase();const path=cleanPath(finalUrl.pathname);if(!STATIC_EXT.test(path)&&!isText(type,path))continue;let content,encoding=null,size;if(isText(type,path)){content=await response.text();size=new TextEncoder().encode(content).byteLength}else{const bytes=new Uint8Array(await response.arrayBuffer());content=b64(bytes);encoding="base64";size=bytes.byteLength}if(total.bytes+size>MAX_BYTES)break;total.bytes+=size;files.push({path,content,content_type:type,encoding});if(type==="text/html"||type==="application/xhtml+xml"||type==="text/css"||type==="text/javascript"||type==="application/javascript"||type==="application/ecmascript")for(const next of refs(content,finalUrl.href)){const nu=new URL(next);if(sameOrigin(nu,root)&&!seen.has(nu.href)&&queue.length<MAX_FILES)queue.push(nu.href)}}const map=new Map(files.map(f=>[f.path,f.path]));for(const file of files)if(file.encoding!=="base64")file.content=localize(file.content,new URL("https://"+root.host+file.path),map);if(!files.some(f=>f.path==="/index.html"))return Response.json({ok:false,error:"no_index_html",files_found:files.length},{status:422});return Response.json({ok:true,source:root.href,title:root.hostname,hostname:root.hostname.toLowerCase().replace(/[^a-z0-9-]/g,"-")+".fair",files,index:true,static:true,limits:{max_files:MAX_FILES,max_bytes:MAX_BYTES}})}