import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const protocols=[["HTTC","httc://","Global Web"],["AMWP","amwp://","American Web"],["EUWP","euwp://","European Web"],["ASWP","aswp://","Asian Web"],["AFWP","afwp://","African Web"],["OCWP","ocwp://","Oceanian Web"]];
const home="httc://home";
const makeTab=(url=home)=>({id:crypto.randomUUID(),url,title:url===home?"Fairwas":url});
const parse=(v)=>{v=v.trim();if(!v)return home;if(protocols.some(([n,p])=>v.toLowerCase().startsWith(p)))return v;if(/^https?:\\/\\//i.test(v))return v;if(/^[a-z0-9.-]+\\.[a-z]{2,}(?:[/:].*)?$/i.test(v))return"httc://"+v;return"httc://search/"+encodeURIComponent(v)};
function App(){const[tabs,setTabs]=useState([makeTab()]),[active,setActive]=useState(0),[address,setAddress]=useState(home),[dark,setDark]=useState(true),[history,setHistory]=useState([]),[bookmarks,setBookmarks]=useState([]);const tab=tabs[active];
useEffect(()=>setAddress(tab?.url||home),[tab?.id,tab?.url]);
useEffect(()=>{const k=e=>{if((e.ctrlKey||e.metaKey)&&e.key==="l"){e.preventDefault();document.querySelector("#address")?.select()}if((e.ctrlKey||e.metaKey)&&e.key==="t"){e.preventDefault();newTab()}if((e.ctrlKey||e.metaKey)&&e.key==="w"){e.preventDefault();closeTab(active)}if((e.ctrlKey||e.metaKey)&&e.key==="d"){e.preventDefault();bookmark()}if(e.altKey&&e.key==="ArrowLeft"){e.preventDefault();history.back()}if(e.altKey&&e.key==="ArrowRight"){e.preventDefault();history.forward()}};addEventListener("keydown",k);return()=>removeEventListener("keydown",k)},[active,tabs]);
function newTab(){setTabs(t=>[...t,makeTab()]);setActive(tabs.length)}
function closeTab(i){if(tabs.length===1)return;setTabs(t=>t.filter((_,n)=>n!==i));setActive(a=>Math.min(a,tabs.length-2))}
function navigate(v=address){const url=parse(v);setTabs(t=>t.map((x,i)=>i===active?{...x,url,title:url===home?"Fairwas":url.split("/")[2]||url}:x));setHistory(h=>url===home?h:[url,...h.filter(x=>x!==url)].slice(0,50))}
function bookmark(){if(tab.url!==home&&!bookmarks.includes(tab.url))setBookmarks(b=>[...b,tab.url])}
return <div className={"app "+(dark?"dark":"light")}><header><div className="brand"><span className="logo">F</span><b>Fairwas</b><span className="protocol">protocol-first browser</span></div><div className="tabs">{tabs.map((t,i)=><button className={"tab "+(i===active?"active":"")} key={t.id} onClick={()=>setActive(i)}><span>{t.title}</span>{tabs.length>1&&<i onClick={e=>{e.stopPropagation();closeTab(i)}}>×</i>}</button>)}<button className="plus" onClick={newTab}>+</button></div><div className="toolbar"><button onClick={()=>history.back()}>←</button><button onClick={()=>history.forward()}>→</button><button onClick={()=>location.reload()}>↻</button><form onSubmit={e=>{e.preventDefault();navigate()}}><span>⌕</span><input id="address" value={address} onChange={e=>setAddress(e.target.value)} aria-label="Dirección"/></form><button onClick={bookmark}>☆</button><button onClick={()=>setDark(x=>!x)}>{dark?"☀":"☾"}</button></div></header><main>{tab.url===home?<section className="home"><div className="hero"><div className="biglogo">F</div><h1>Fairwas</h1><p>Una web con protocolos propios.</p><form onSubmit={e=>{e.preventDefault();navigate()}}><input autoFocus placeholder="Escribe una dirección o búsqueda" onChange={e=>setAddress(e.target.value)}/><button>Ir</button></form></div><div className="protocols">{protocols.map(([name,prefix,desc])=><button key={name} onClick={()=>navigate(prefix+"home")}><strong>{name}</strong><span>{prefix}</span><small>{desc}</small></button>)}</div><div className="info"><span>HTTC · AMWP · EUWP · ASWP · AFWP · OCWP</span><span>{history.length} visitas · {bookmarks.length} favoritos</span></div></section>:<section className="page"><div className="pagehead"><span className="scheme">{tab.url.split(":")[0].toUpperCase()}</span><h2>{tab.title}</h2><p>{tab.url}</p></div><div className="notice">Fairwas ha recibido esta dirección mediante un protocolo propio. El motor de resolución y transporte se conectará aquí cuando implementemos las capas de red.</div></section>}</main></div>}
createRoot(document.getElementById("root")).render(<App/>);